### ISSUE TITLE
Improve markdown code highlighting styles in CSS

### ISSUE THREAD

**Issue by asrient** [dsc-iem/blog#19]
## Skills required
(You don't need to know Django or Javascript for this)
- HTML
- CSS

## What to do
When writing a blog, a code block is declared in markdown as 
```
```javascript
function fancyAlert(arg) {
  if(arg) {
    $.facebox({div:'#foo'})
  }
}
 ` ``
```
when rendered, it takes form as:
```html
<pre>
<code>
<span class="kd">function</span> 
<span class="nx">fancyAlert</span>
<span class="p">(</span>
...
</code>
</pre>
```
Your main work is to update `dscblog/static/styles/emacs.css` file, 
change the colors and other attributes to make it look better.
It's up to you what colors to pick, just don't make it look too clumsy or too dull.
You will find codes like,
```css
[data-theme="dark"] code .hll { color: #ffffc4 }
```
These codes are the optimized versions for Dark mode,
You need to make sure, it looks good in both modes.

**Comment by naijatechgirle** [comment]
Please assign me

**Comment by asrient** [comment]
Hi!
Thanks for showing interest in our project. You can start working on this issue now.
Happy coding

**Comment by SHIVANI0708** [comment]
please assign this to can do this work

**Comment by SHIVANI0708** [comment]
Please assign this to me I can do this work

**Comment by asrient** [comment]
> Please assign this to me I can do this work

Hi @SHIVANI0708 , we have already assigned it to Kelechi-Eluagu this time, you can look for other issues that are not assigned yet.
Do keep a watch for more upcoming issues as we post them. Best of luck!

**Comment by naijatechgirle** [comment]
Please assign me

**Comment by asrient** [comment]
> Please assign me

@Kelechi-Eluagu You have already been assigned this issue.
