### ISSUE TITLE
Add blogs grid to the blog page

### ISSUE THREAD

**Issue by asrient** [dsc-iem/blog#20]
## Skills required

- HTML
- Django (templates)

## References

- ` index.html` page

## What to do

`blogsGrid.html` component renders a grid with given blog items in a parent page.
Add `blogsGrid.html`, which lives in `dscblog/pages/blocks/` dir, to `blog.html`, the blog
template at the end.
This should act as More blogs suggestions at shows up at the end of an article.
Take a look at the `index page` rendering, this should act the same way, you can use the same
function `Blog.top25()` to get the blogs or something similar (maybe a variant with 10 no of blogs instead).

## Files to work with

-  pages/blocks/blogsGrid.html
-  pages/blog.html
-  models.py
-  paths.py

**Comment by ketanpandey01** [comment]
Is this open? Can u assign it to me?

**Comment by asrient** [comment]
Hi @ketanpandey01 
Thanks for showing interest in our project. You can start working on this issue now.
Feel free to contact us here for any help related to this issue.
Happy coding

**Comment by asrient** [comment]
Hi, @ketanpandey01 
Any updates on this issue?
Have you stated working on this?

**Comment by ketanpandey01** [comment]
Hi @asrient ,
Sorry to inform you, I didn't get time to work on this.
You can assign it to someone else.
