### ISSUE TITLE
Add a Done button to blog editor

### ISSUE THREAD

**Issue by asrient** [dsc-iem/blog#21]
## Skills required

- Javascript
- HTML, CSS

## What to do

The current blog editor only contains the editor, 
but we need a header on top of the actual editor showing its title and a `Done` button.
The done button will resave the file and when done go to the blog page.
The design of the header is up to you, just make sure it matches with the rest of the site.
*postion should be fixed.*

## Files to work with

- pages/blogEditor.html
- static/styles/blogEditor.css

**Comment by niksseif** [comment]
@asrient I would like to contribute to this repo. If this issue is still open can you assign it to me?

**Comment by asrient** [comment]
Hi!
Thanks for showing interest in our project. You can start working on this issue now.
Happy coding

**Comment by asrient** [comment]
Hi @niksseif any updates on this?

**Comment by o3661606** [comment]
@asrient seems no update from the original assignee, therefore I've completed this.

**Comment by asrient** [comment]
Thank you @o3661606 for your work!
