### ISSUE TITLE
Build the followers page

### ISSUE THREAD

**Issue by asrient** [dsc-iem/blog#22]
## Skills required

- html, css
- Django

## What to do

You need to build a page which will show all the current user's followers.
This should be like any others pages in the site, like `index', `blog`, 
only visible to logged in users.
Use the function `get_followers()` of the user object.
The URL should be `/followers`
Build a generic user list view in `pages/blocks` directory.

## Files to work with

- paths.py
- urls.py
- pages/followers.py (new)
- pages//blocks/usersList.html (new)

**Comment by Antsthebul** [comment]
Can you assign this to me?

**Comment by asrient** [comment]
Hi @Antsthebul 
Thanks for showing interest in our project. You can start working on this issue now.
Feel free to contact us here for any help related to this issue.
Happy coding

**Comment by asrient** [comment]
Hi @Antsthebul what's the current status? Are you facing any difficulties working on this issue?

**Comment by Antsthebul** [comment]
> Hi @Antsthebul what's the current status? Are you facing any difficulties working on this issue?

Ive made a new PR.

**Comment by asrient** [comment]
Thanks, I will look into the PR now, great work!
